version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    container_name: startup_profit_fastapi
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    container_name: startup_profit_streamlit
    restart: unless-stopped